language: ruby
cache: bundler
script: bundle exec rspec
before_install: gem install bundler -v 1.10.6
rvm:
  - "2.4.1"

gemfile:
  - gemfiles/Rails-5.1.gemfile
  - gemfiles/Rails-5.0.gemfile
  - gemfiles/Rails-4.2.gemfile
  - gemfiles/Rails-head.gemfile

matrix:
  include:
    # Test Rails 4.0–4.1 against Ruby 2.3
    - rvm: "2.3"
      gemfile: gemfiles/Rails-4.1.gemfile

    - rvm: "2.3"
      gemfile: gemfiles/Rails-4.0.gemfile

    # Test gem against other Rubies, use the best-matching Rails version
    - rvm: "2.3"
      gemfile: gemfiles/Rails-5.1.gemfile

    - rvm: "2.2"
      gemfile: gemfiles/Rails-4.2.gemfile

    - rvm: "2.1"
      gemfile: gemfiles/Rails-4.2.gemfile

    - rvm: "2.0"
      gemfile: gemfiles/Rails-4.2.gemfile

    - rvm: "1.9.3"
      gemfile: gemfiles/Rails-4.2.gemfile

    - rvm: "rbx-2"
      gemfile: gemfiles/Rails-4.2.gemfile

    - rvm: "rbx-3"
      gemfile: gemfiles/Rails-5.1.gemfile

    - rvm: "jruby-19mode"
      gemfile: gemfiles/Rails-4.2.gemfile

    - rvm: "ruby-head"
      gemfile: gemfiles/Rails-5.1.gemfile

    - rvm: "jruby-head"
      gemfile: gemfiles/Rails-5.1.gemfile

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
    - gemfile: gemfiles/Rails-head.gemfile
